POST {{endpoint}}/flow
Content-Type: application/json

{
  "name": "test-1",
  "author": "author-1"
}

###
PATCH {{endpoint}}/flow/2
Content-Type: application/json

{
  "name": "test-2",
  "author": "author-2"
}

###
GET {{endpoint}}/flow/2
Accept: application/json

###
GET {{endpoint}}/flow
Accept: application/json

###
DELETE {{endpoint}}/flow/1
Accept: application/json

###