POST {{endpoint}}/edge
Content-Type: application/json

{
  "flowId": 1
}

###
PATCH {{endpoint}}/edge/1
Content-Type: application/json

{
  "dataType": "Label",
  "data": {
    "label": "label-1"
  },
  "targetNodeId": 1
}

###
GET {{endpoint}}/edge/1
Accept: application/json

###
DELETE {{endpoint}}/edge/1
Accept: application/json

###