app:
  port: 9001
  nodeEnv: development

db:
  type: better-sqlite3  # mysql or better-sqlite3
  mysql:
    host: localhost
    port: 9106
    user: root
    password: password
    database: notebook
  better-sqlite3:
    database: database/notebook.db

storage:
  s3:
    endpoint: http://localhost:9109 # minio endpoint
    region: us-east-1
    secretKey: minioadmin
    accessKey: minioadmin
    forcePathStyle: true
    signatureVersion: v4
  buckets: # override buckets, see STORAGE_BUCKET_NAME
    uploaded: uploaded
    generated: generated
    temp: temp

inngest:
  isDev: true
  baseUrl: http://localhost:9108

ai:
  models: # create a aksk.yaml in config folder to override !!
    - id: gpt-4-turbo@openai                    # required
      provider: openai                          # required
      modelName: gpt-4-turbo                    # required
      apiKey: my-api-key                        # required
      baseUrl: https://api.openai.com/v1/models # required
      proxy: http://localhost:7890              # optional
      disabled: true                            # optional
      features:                                 # optional, default: ['text-generation']
        - text-generation
        - reasoning
        - vision                       # image recognition
        - image-generation

