/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdgeAddInput } from './edge-add-input';

/**
 * 
 * @export
 * @interface BatchEdgeAddInput
 */
export interface BatchEdgeAddInput {
    /**
     * 
     * @type {Array<EdgeAddInput>}
     * @memberof BatchEdgeAddInput
     */
    'edges': Array<EdgeAddInput>;
}

