/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentSlim
 */
export interface DocumentSlim {
    /**
     * 
     * @type {number}
     * @memberof DocumentSlim
     */
    'flowId': number;
    /**
     * 
     * @type {string}
     * @memberof DocumentSlim
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof DocumentSlim
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof DocumentSlim
     */
    'updatedAt': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DocumentSlim
     */
    'nodeIds': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DocumentSlim
     */
    'edgeIds': Array<string>;
}

