/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdgeEntity } from './edge-entity';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeEntity } from './node-entity';

/**
 * 
 * @export
 * @interface DocumentFull
 */
export interface DocumentFull {
    /**
     * 
     * @type {number}
     * @memberof DocumentFull
     */
    'flowId': number;
    /**
     * 
     * @type {string}
     * @memberof DocumentFull
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof DocumentFull
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof DocumentFull
     */
    'updatedAt': string;
    /**
     * 
     * @type {Array<NodeEntity>}
     * @memberof DocumentFull
     */
    'nodes': Array<NodeEntity>;
    /**
     * 
     * @type {Array<EdgeEntity>}
     * @memberof DocumentFull
     */
    'edges': Array<EdgeEntity>;
}

