/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdgeHandleEnum } from './edge-handle-enum';

/**
 * 
 * @export
 * @interface EdgeLayout
 */
export interface EdgeLayout {
    /**
     * Source handle position
     * @type {EdgeHandleEnum}
     * @memberof EdgeLayout
     */
    'sourceHandle'?: EdgeHandleEnum;
    /**
     * Target handle position
     * @type {EdgeHandleEnum}
     * @memberof EdgeLayout
     */
    'targetHandle'?: EdgeHandleEnum;
}



