/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EdgeAddInput
 */
export interface EdgeAddInput {
    /**
     * 
     * @type {number}
     * @memberof EdgeAddInput
     */
    'flowId': number;
    /**
     * 
     * @type {number}
     * @memberof EdgeAddInput
     */
    'sourceNodeId'?: number;
    /**
     * 
     * @type {number}
     * @memberof EdgeAddInput
     */
    'targetNodeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EdgeAddInput
     */
    'label'?: string;
}

