/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileMetadata } from './file-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { StorageBucketName } from './storage-bucket-name';

/**
 * 
 * @export
 * @interface FileEntity
 */
export interface FileEntity {
    /**
     * 
     * @type {StorageBucketName}
     * @memberof FileEntity
     */
    'bucket': StorageBucketName;
    /**
     * 
     * @type {number}
     * @memberof FileEntity
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof FileEntity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FileEntity
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof FileEntity
     */
    'path': string;
    /**
     * 
     * @type {FileMetadata}
     * @memberof FileEntity
     */
    'metadata': FileMetadata;
    /**
     * 
     * @type {string}
     * @memberof FileEntity
     */
    'updatedAt': string;
}



