/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileMetadata
 */
export interface FileMetadata {
    /**
     * filename extension
     * @type {string}
     * @memberof FileMetadata
     */
    'extension': string;
    /**
     * file size, unit: byte
     * @type {number}
     * @memberof FileMetadata
     */
    'size': number;
    /**
     * MIME
     * @type {string}
     * @memberof FileMetadata
     */
    'mime': string;
    /**
     * image file width
     * @type {number}
     * @memberof FileMetadata
     */
    'width'?: number;
    /**
     * image file height
     * @type {number}
     * @memberof FileMetadata
     */
    'height'?: number;
}

