/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FlowEntityPopulatedCount
 */
export interface FlowEntityPopulatedCount {
    /**
     * node count
     * @type {number}
     * @memberof FlowEntityPopulatedCount
     */
    'nodeCount'?: number;
    /**
     * edge count
     * @type {number}
     * @memberof FlowEntityPopulatedCount
     */
    'edgeCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof FlowEntityPopulatedCount
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof FlowEntityPopulatedCount
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FlowEntityPopulatedCount
     */
    'updatedAt': string;
}

