/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdgeEntity } from './edge-entity';
// May contain unused imports in some cases
// @ts-ignore
import type { GeneratingTaskInputPrompt } from './generating-task-input-prompt';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeEntity } from './node-entity';

/**
 * 
 * @export
 * @interface GeneratingTaskInput
 */
export interface GeneratingTaskInput {
    /**
     * model id
     * @type {string}
     * @memberof GeneratingTaskInput
     */
    'modelId'?: string;
    /**
     * prompt to trigger generating task
     * @type {Array<GeneratingTaskInputPrompt>}
     * @memberof GeneratingTaskInput
     */
    'prompt'?: Array<GeneratingTaskInputPrompt>;
    /**
     * generating to target node
     * @type {NodeEntity}
     * @memberof GeneratingTaskInput
     */
    'targetNodeSnapshot'?: NodeEntity;
    /**
     * 
     * @type {Array<Array<NodeEntity>>}
     * @memberof GeneratingTaskInput
     */
    'sourceNodeSnapshots': Array<Array<NodeEntity>>;
    /**
     * generating from source edges
     * @type {Array<EdgeEntity>}
     * @memberof GeneratingTaskInput
     */
    'edgeSnapshots'?: Array<EdgeEntity>;
}

