/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GeneratedUsage
 */
export interface GeneratedUsage {
    /**
     * prompt tokens
     * @type {number}
     * @memberof GeneratedUsage
     */
    'promptTokens': number;
    /**
     * completion tokens
     * @type {number}
     * @memberof GeneratedUsage
     */
    'completionTokens': number;
    /**
     * total tokens
     * @type {number}
     * @memberof GeneratedUsage
     */
    'totalTokens': number;
}

