/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GeneratingTaskInput } from './generating-task-input';
// May contain unused imports in some cases
// @ts-ignore
import type { GeneratingTaskOutput } from './generating-task-output';
// May contain unused imports in some cases
// @ts-ignore
import type { GeneratingTaskStatusEnum } from './generating-task-status-enum';

/**
 * 
 * @export
 * @interface GeneratingTaskEntity
 */
export interface GeneratingTaskEntity {
    /**
     * 
     * @type {GeneratingTaskStatusEnum}
     * @memberof GeneratingTaskEntity
     */
    'status': GeneratingTaskStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof GeneratingTaskEntity
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof GeneratingTaskEntity
     */
    'flowId': number;
    /**
     * 
     * @type {number}
     * @memberof GeneratingTaskEntity
     */
    'targetNodeId': number;
    /**
     * 
     * @type {GeneratingTaskInput}
     * @memberof GeneratingTaskEntity
     */
    'input': GeneratingTaskInput;
    /**
     * 
     * @type {GeneratingTaskOutput}
     * @memberof GeneratingTaskEntity
     */
    'output': GeneratingTaskOutput;
    /**
     * 
     * @type {string}
     * @memberof GeneratingTaskEntity
     */
    'updatedAt': string;
}



