/* tslint:disable */
/* eslint-disable */
/**
 * Notebook Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NodeAddInput
 */
export interface NodeAddInput {
    /**
     * 
     * @type {number}
     * @memberof NodeAddInput
     */
    'flowId': number;
    /**
     * 
     * @type {number}
     * @memberof NodeAddInput
     */
    'positionX'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeAddInput
     */
    'positionY'?: number;
    /**
     * 
     * @type {string}
     * @memberof NodeAddInput
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeAddInput
     */
    'dataType'?: DataTypeEnum;
}

export const DataTypeEnum = {
    Text: 'TEXT',
    Image: 'IMAGE'
} as const;

export type DataTypeEnum = typeof DataTypeEnum[keyof typeof DataTypeEnum];


